// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc_CwMWxhetmHaBYmsJtdKGFa7OEkVn7Q',
    appId: '1:196182196943:web:c66d68cf7c13c1031aedba',
    messagingSenderId: '196182196943',
    projectId: 'cadastro-de-coisas',
    authDomain: 'cadastro-de-coisas.firebaseapp.com',
    databaseURL: 'https://cadastro-de-coisas-default-rtdb.firebaseio.com',
    storageBucket: 'cadastro-de-coisas.firebasestorage.app',
    measurementId: 'G-6K78HQDM81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQVPc_S_Le1pXy4uBQRWDkcSi58DNDP0M',
    appId: '1:196182196943:android:994a54319aa053bf1aedba',
    messagingSenderId: '196182196943',
    projectId: 'cadastro-de-coisas',
    databaseURL: 'https://cadastro-de-coisas-default-rtdb.firebaseio.com',
    storageBucket: 'cadastro-de-coisas.firebasestorage.app',
  );

}